<Mensagem>:
    BoxLayout:
        orientation:'vertical'
        ScrollView:
            # Talvez esteja aqui o problema da imagem (da Cayla), fica embaixo
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height

# É uma classe BoxLayout
<CaylaFala>:
    size_hint:None, None
    height:self.minimum_height
    orientation: 'horizontal'
    padding: 0, 0, 0, 0
    spacing:10
    # Adiciona Cayla desse lado <-
    Button:
        anchor_y: 'top'
        size_hint: None, None
        border: 0, 0, 0, 0
        background_normal:'cayla_rosa.png'
        background_down: 'cayla_rosa.png'
