<Mensagem>:
    BoxLayout:
        orientation:'vertical'
        ScrollView:
            # Talvez esteja aqui o problema da imagem (da Cayla), fica embaixo
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint: None, None
                height:self.minimum_height+10

# É uma classe BoxLayout
<CaylaFala>:
    id:mini
    size_hint:None, None
    height:self.minimum_height
    orientation: 'horizontal'
    padding: 0, 20, 0, 10
    spacing:10
