<Mensagem>:
    BoxLayout:
        orientation:'vertical'
        ScrollView:
            # Talvez esteja aqui o problema da imagem (da Cayla), fica embaixo
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint: None, None
                height:self.minimum_height+10

# É uma classe BoxLayout
<CaylaFala>:
    id:mini
    size_hint:None, None
    height:self.minimum_height
    orientation: 'horizontal'
    padding: 0, 15, 0, 10
    spacing:10
    # Adiciona Cayla desse lado <-
    Button:
        id: cay
        size_hint: None, None
        pos_hint: {'top': 1.1}
        border: 0, 0, 0, 0
        background_normal:'cayla_rosa.png'
        background_down: 'cayla_rosa.png'
